export const EDIT_SURVEY_PROPERTY = 'CHANGE_NEW_SURVEY_INPUT_VALUE';
export const ADD_QUESTION = 'ADD_QUESTION';
export const REMOVE_QUESTION = 'REMOVE_QUESTION';
export const EDIT_QUESTION_PROPERTY = 'CHANGE_NEW_SURVEY_QUESTION_PROPERTY';
